version: '2'
services:
   builder:
      build: build
      volumes:
        - ./vol:/var/lib/tomcat8/webapps
   tomcat:
      build: tomcat
      links:
        - build
      volumes_from:
        - builder
      ports:
        - "8080:8080"
